version: "3.3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    network_mode: "host"
  bnext:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    network_mode: "host"
