version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  bnext:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=testing
      - RESTAPI_VERSION=v1
      - RESTAPI_PORT=8080
    volumes:
      - ./:/usr/src/app
    network_mode: "host"
